[package]
name = "chess_rs"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "2.9.3"

[profile.release]
codegen-units = 1
lto = true
strip = true
